# Generated by Django 4.2.25 on 2025-11-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='wins_needed',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
