# Generated by Django 4.2.25 on 2025-11-27 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0003_round"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchmakingQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("matched", "Matched"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "preferred_difficulty",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="any",
                        help_text="Preferred bot difficulty if matched with bot",
                        max_length=20,
                    ),
                ),
                (
                    "allow_bots",
                    models.BooleanField(
                        default=True, help_text="Allow matching with bot players"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_matches",
                        to="game.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matchmaking Queue Entry",
                "verbose_name_plural": "Matchmaking Queue Entries",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("random", "Random"),
                            ("counter", "Counter Strategy"),
                            ("pattern", "Pattern Based"),
                            ("adaptive", "Adaptive"),
                        ],
                        default="random",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "response_time_range",
                    models.JSONField(
                        default=dict,
                        help_text='Min/max response time in seconds: {"min": 1.0, "max": 3.0}',
                    ),
                ),
                (
                    "win_rate",
                    models.FloatField(
                        default=0.5,
                        help_text="Target win rate for adaptive strategy (0.0-1.0)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this bot is available for matchmaking",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Player",
                "verbose_name_plural": "Bot Players",
            },
        ),
    ]
