# Generated by Django 4.2.25 on 2025-11-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bot_difficulty",
            field=models.CharField(
                blank=True,
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                help_text="Bot difficulty level for AI players",
                max_length=20,
                verbose_name="bot difficulty",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_bot",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user is a bot player",
                verbose_name="is bot",
            ),
        ),
    ]
